### ISSUE TITLE
cant install steam

### ISSUE THREAD

**Issue by suomilanittaja** [PhoenicisOrg/phoenicis#1448]
used operating system ubuntu 18.04
it get error when downloading

**Comment by plata** [comment]
Please be a bit more precise (e.g. exact error message, logs etc). With the current information we will not be able to help you.

**Comment by plata** [comment]
Steam app has been fixed. Should work now.

**Comment by suomilanittaja** [comment]
still not working
javax.script.ScriptException: Error while calculating checksum for "/home/sl/.Phoenicis/tmp/phoenicis1378167552069522274.exe". 

Expected = e930dbdb3bc638f772a8fcd92dbcd0919c924318
Actual = 4b1b85ec2499a4ce07c89609b256923a4fc479e5 in <eval> at line number 134 at column number 16
	at jdk.nashorn.api.scripting.NashornScriptEngine.throwAsScriptException(NashornScriptEngine.java:470)
	at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:454)
	at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:406)
	at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:402)
	at jdk.nashorn.api.scripting.NashornScriptEngine.eval(NashornScriptEngine.java:155)
	at javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:264)
	at org.phoenicis.scripts.nashorn.NashornEngine.eval(NashornEngine.java:50)
	at org.phoenicis.scripts.nashorn.NashornScriptInterpreter.runScript(NashornScriptInterpreter.java:35)
	at org.phoenicis.scripts.interpreter.BackgroundScriptInterpreter.lambda$runScript$0(BackgroundScriptInterpreter.java:35)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: <eval>:134:16 Error while calculating checksum for "/home/sl/.Phoenicis/tmp/phoenicis1378167552069522274.exe". 

Expected = e930dbdb3bc638f772a8fcd92dbcd0919c924318
Actual = 4b1b85ec2499a4ce07c89609b256923a4fc479e5
	at jdk.nashorn.internal.runtime.ECMAException.create(ECMAException.java:113)
	at jdk.nashorn.internal.scripts.Script$Recompilation$292$2364$\^eval\_.get([utils, functions, net, download]:134)
	at jdk.nashorn.internal.scripts.Script$Recompilation$285$875A$\^eval\_._installationCommand([engines, wine, quick_script, online_installer_script]:40)
	at jdk.nashorn.internal.scripts.Script$Recompilation$283$565$\^eval\_.go([engines, wine, quick_script, installer_script]:30)
	at jdk.nashorn.internal.scripts.Script$Recompilation$271$216$\^eval\_.run(<eval>:9)
	at org.phoenicis.scripts.Installer$$NashornJavaAdapter.run(Unknown Source)
	at jdk.nashorn.internal.scripts.Script$246$\^eval\_.:program(<eval>:25)
	at jdk.nashorn.internal.runtime.ScriptFunctionData.invoke(ScriptFunctionData.java:637)
	at jdk.nashorn.internal.runtime.ScriptFunction.invoke(ScriptFunction.java:494)
	at jdk.nashorn.internal.runtime.ScriptRuntime.apply(ScriptRuntime.java:393)
	at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:449)
	... 10 more

**Comment by plata** [comment]
Are you sure that your software and scripts repository are up to date? Please provide the git revisions. @mlaradji could you check if Steam is still working for you?

**Comment by suomilanittaja** [comment]
yes they maybe are but epic games get similar error

**Comment by mlaradji** [comment]
Steam still installs fine on my setup, but only when using the `master` branch of `https://github.com/PhoenicisOrg/scripts`. Judging from the error message, @suomilanittaja it seems that you are using the `patch-5.0` branch (which is the default). Adding the `master` branch to the repository list with the correct priority should fix this problem.

**Comment by mlaradji** [comment]
@suomilanittaja Glad that the original issue is fixed!

Re: Online access. I seem to be facing the same problem. Though I can login and I can see my library, attempting to install a game results in the error message:

> Steam - Error
> An error occured while installing Dota 2 (content servers unreachable)
> 
> See the Steam support site for more information

Other web services also do not seem to be working. When attempting to access the store, `steamwebhelper.exe` crashes. Perhaps this is related to the issue at hand.

@suomilanittaja Are you facing a similar issue?

**Comment by plata** [comment]
Do you have the content server issue also when using Steam QuickScripts (not the Steam app)? I had implemented a fix for it there. Maybe this should be added to the Steam script as well.

**Comment by suomilanittaja** [comment]
idk what you are meaning with QuickScripts but if it work add it to steam script

**Comment by plata** [comment]
I'm referring to:
https://github.com/PhoenicisOrg/scripts/blob/d28dd865c82831c33b3dde2f945b534bf158e44a/Engines/Wine/QuickScript/Steam%20Script/script.js#L82

@mlaradji would you mind giving this a try? You can more or less copy that code to the `postInstall` step of the Steam script.

**Comment by suomilanittaja** [comment]
tell me when it is fixed and if i need to do something that i get it to working.

**Comment by suomilanittaja** [comment]
Fixed? and is new version coming soon.

**Comment by plata** [comment]
I just checked. My proposed fix doesn't work because the config file is not available at that point yet (it is created when you first log in).

**Comment by plata** [comment]
Check https://github.com/PhoenicisOrg/scripts/pull/709
